name: ncd
version: 0.2.11
description: >-
  - fixed_length
  - delimiter_based
  - length_field_based
  - line_based

homepage: https://github.com/whiteCcinn/netty-codec-dart
documentation: https://github.com/whiteCcinn/netty-codec-dart/blob/main/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'